#!/bin/bash

#
# develop
#

images () {
  docker compose build --parallel
}

up () {
  docker compose up --detach shell
}

shell () {
  up && docker compose exec shell /bin/berglas exec -- /bin/bash -l
}

rootshell () {
  up && docker compose exec -u root shell /bin/bash -l
}

down () {
  docker compose stop
}

clean () {
  docker compose rm -s -f -v
}

#
# workflow
#

test () {
  echo $HOME
  whoami
  up && docker compose exec shell /app/bin/test
}

push () {
  docker compose push
  docker compose convert --resolve-image-digests --format json |
  jq '.services | map_values(.image)'
}

docs () {
  (sleep 3; open http://localhost:8000) &
  docker compose run --rm --service-ports docs
}

#
# boilerplate
#

set -e

list () {
  compgen -A function
}

if list | grep -qFx -- "${1:-}"
then "$@"; exit $?
else
  printf "unknown command: %s\n" "${1:-}" >&2
  exit 1
fi
