# Development flags file
- --service-account: rt-gcp-django@goodlittlescript-io-dev.iam.gserviceaccount.com
- --set-env-vars: DJANGO_SECRET_KEY=sm://goodlittlescript-io-dev/gcp-django--secret-key
- --set-env-vars: DJANGO_ALLOWED_HOSTS=gcp-django.dev.goodlittlescript.io:gcp-django-onmhavhggq-uc.a.run.app
- --set-env-vars: DATA_BUCKET=goodlittlescript-io-dev-us-central1-gcp-django-data
- --set-env-vars: CLOUDTASKS_SERVICE_ACCOUNT_EMAIL=rt-gcp-django@goodlittlescript-io-dev.iam.gserviceaccount.com
- --set-env-vars: CLOUDRUN_AUDIENCE=gcp-django-onmhavhggq-uc.a.run.app
- --set-env-vars: CLOUDTASKS_QUEUE=gcp-django
- --project: goodlittlescript-io-dev
- --region: us-central1
