#!/bin/bash
. test/integration/helpers

export base_url="http://localhost:8081"
unset GUNICORN_OPTS

background ./bin/run -b "${base_url#http://}"
wait_until healthcheck 

test_storage () {
  get 'storage/get'
  before_time_s="$(last_response | jq  -r '.lastUpdate | fromdate')"

  get 'storage/set'
  after_time_s="$(last_response | jq  -r '.lastUpdate | fromdate')"

  [ "$before_time_s" -lt "$after_time_s" ]
  assert_status "$?" 0 "lastUpdate was not updated"

  get 'storage/get'
  confirm_time_s="$(last_response | jq  -r '.lastUpdate | fromdate')"

  [ "$after_time_s" = "$confirm_time_s" ]
  assert_status "$?" 0 "lastUpdate was not confirmed"
}

. ts
