name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: us-central1-docker.pkg.dev/goodlittlescript-io-dev
    steps:
    - uses: actions/checkout@v3
    - name: Set Env
      run: |-
        echo "RUNTIME_IMAGE=${DOCKER_REPO}/gcp-django/runtime:${GITHUB_SHA}" >> "$GITHUB_ENV"
    - name: Build images
      run: ./Projectfile images
    - name: Test images
      run: ./Projectfile test
    - name: Push images
      run: ./Projectfile push
