name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOURCE_REPO: us-central1-docker.pkg.dev/goodlittlescript-io-dev/gcp-django
  IMAGE_FILE: images.json

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/166389283410/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-prvdr'
        service_account: 'dt-gcp-django@goodlittlescript-io-dev.iam.gserviceaccount.com'
    - name: 'Authenticate to Docker Repo'
      run: gcloud auth configure-docker "$(sed -e 's|/.*||' <<<"$SOURCE_REPO")"
    - name: 'Authenticate in Docker Compose'
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=/app/$(basename "$GOOGLE_APPLICATION_CREDENTIALS")" >> docker-compose.env
    - name: 'Set Env'
      run: |-
        echo "RUNTIME_IMAGE=${SOURCE_REPO}/runtime:${GITHUB_SHA}" >> "$GITHUB_ENV"
    - name: Build images
      run: ./Projectfile images
    - name: Test images
      run: ./Projectfile test
    - name: Push images
      run: ./Projectfile push > "$IMAGE_FILE"
    - uses: actions/upload-artifact@master
      with:
        name: image_file
        path: ${{env.IMAGE_FILE}}

  deploy-development:
    name: Deploy Development
    needs: build
    uses: ./.github/workflows/cloudrun.yml
    with:
      environment: development
      service_name: gcp-django
      image_name: shell
      source_repo: ${{ env.SOURCE_REPO }}
      target_repo: us-central1-docker.pkg.dev/goodlittlescript-io-dev/gcp-django
      workload_identity: dt-gcp-django@goodlittlescript-io-dev.iam.gserviceaccount.com'

  deploy-production:
    name: Deploy Production
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/cloudrun.yml
    with:
      environment: production
      service_name: gcp-django
      image_name: shell
      source_repo: ${{ env.SOURCE_REPO }}
      target_repo: us-central1-docker.pkg.dev/goodlittlescript-io-prd/gcp-django
      workload_identity: dt-gcp-django@goodlittlescript-io-prd.iam.gserviceaccount.com'
