name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REPO: us-central1-docker.pkg.dev/goodlittlescript-io-dev/gcp-django
  IMAGES_FILE: images.json

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/166389283410/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-prvdr'
        service_account: 'dt-gcp-django@goodlittlescript-io-dev.iam.gserviceaccount.com'
    - name: 'Authenticate to Docker Repo'
      run: gcloud auth configure-docker "$(sed -e 's|/.*||' <<<"$DOCKER_REPO")"
    - name: 'Authenticate in Docker Compose'
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=/app/$(basename "$GOOGLE_APPLICATION_CREDENTIALS")" >> docker-compose.env
    - name: 'Set Env'
      run: |-
        echo "RUNTIME_IMAGE=${DOCKER_REPO}/runtime:${GITHUB_SHA}" >> "$GITHUB_ENV"
    - name: Build images
      run: ./Projectfile images
    - name: Test images
      run: ./Projectfile test
    - name: Push images
      run: ./Projectfile push > "$IMAGES_FILE"
    - uses: actions/upload-artifact@master
      with:
        name: image_digests
        path: ${{env.IMAGES_FILE}}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      SERVICE_NAME: gcp-django
      IMAGE_NAME: shell
    steps:
    - uses: actions/checkout@v3
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/166389283410/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-prvdr'
        service_account: 'dt-gcp-django@goodlittlescript-io-dev.iam.gserviceaccount.com'
    - uses: actions/download-artifact@master
      with:
        name: image_digests
    - name: 'Set Env'
      run: |-
        echo "IMAGE256=$(jq -r '.[env.IMAGE_NAME]' "$IMAGES_FILE")" >> "$GITHUB_ENV"
        echo "REVISION_TAG=sha-$(head -c 7 <<<"$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "REVISION_SUFFIX=$GITHUB_RUN_ID" >> "$GITHUB_ENV"
    - name: 'Deploy CloudRun'
      run: |-
        printf "Service: %s-%s:%s\n" "$SERVICE_NAME" "$REVISION_SUFFIX" "$REVISION_TAG"
        printf "Image: %s\n" "$IMAGE256"
        gcloud beta run deploy "$SERVICE_NAME" --image="$IMAGE256" --revision-suffix "$REVISION_SUFFIX" --tag "$REVISION_TAG" --flags-file=config/dev.yml

  deploy-prd:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: prd
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      SERVICE_NAME: gcp-django
      IMAGE_NAME: shell
    steps:
    - uses: actions/checkout@v3
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/166389283410/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-prvdr'
        service_account: 'dt-gcp-django@goodlittlescript-io-prd.iam.gserviceaccount.com'
    - uses: actions/download-artifact@master
      with:
        name: image_digests
    - name: 'Set Env'
      run: |-
        echo "IMAGE256=$(jq -r '.[env.IMAGE_NAME]' "$IMAGES_FILE")" >> "$GITHUB_ENV"
        echo "REVISION_TAG=sha-$(head -c 7 <<<"$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "REVISION_SUFFIX=$GITHUB_RUN_ID" >> "$GITHUB_ENV"
    - name: 'Deploy CloudRun'
      run: |-
        printf "Service: %s-%s:%s\n" "$SERVICE_NAME" "$REVISION_SUFFIX" "$REVISION_TAG"
        printf "Image: %s\n" "$IMAGE256"
        gcloud beta run deploy "$SERVICE_NAME" --image="$IMAGE256" --revision-suffix "$REVISION_SUFFIX" --tag "$REVISION_TAG" --flags-file=config/prd.yml
