name: Publish Pages
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Build
        run: ./Projectfile docs build
      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
